// CSE 154 ASCIIMation
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// (Paste this code as the contents of your myanimation.js file.)

var CUSTOM =
"  o  \n" + 
" /#\\_____\n" + 
" / / \n" + 
"=====\n" + 
"       \\o/ \n" + 
"____ #  \n" + 
"     _/ \\_\n" + 
"=====\n" + 
"             o\n" + 
"______  #\\\n" + 
"           //\n" + 
"=====\n" + 
"        o\n" + 
"=====\n" + 
"            o\n" + 
"=====\n" + 
"                o\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;
